IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'DataScriptInfo')
CREATE TABLE dbo.DataScriptInfo(
	Id				UNIQUEIDENTIFIER PRIMARY KEY,
	ExecutedDate	DATETIMEOFFSET NOT NULL,
	[Hash]			NVARCHAR(4000) NOT NULL
)