'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Symmex.Snowflake.DataDeployment.Sql.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = &apos;{0}&apos;)
        '''CREATE DATABASE {0}
        '''GO
        '''
        '''USE {0}
        '''GO.
        '''</summary>
        Friend ReadOnly Property EnsureDatabase() As String
            Get
                Return ResourceManager.GetString("EnsureDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = &apos;dbo&apos; AND TABLE_NAME = &apos;DataScriptInfo&apos;)
        '''CREATE TABLE dbo.DataScriptInfo(
        '''	Id				UNIQUEIDENTIFIER PRIMARY KEY,
        '''	ExecutedDate	DATETIMEOFFSET NOT NULL,
        '''	[Hash]			NVARCHAR(4000) NOT NULL
        ''')
        '''GO.
        '''</summary>
        Friend ReadOnly Property EnsureDataScriptInfoTable() As String
            Get
                Return ResourceManager.GetString("EnsureDataScriptInfoTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Id, ExecutedDate, [Hash]
        '''FROM dbo.DataScriptInfo.
        '''</summary>
        Friend ReadOnly Property GetDataScriptInfos() As String
            Get
                Return ResourceManager.GetString("GetDataScriptInfos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO dbo.DataScriptInfo(Id, ExecutedDate, [Hash]) VALUES(&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;)
        '''GO.
        '''</summary>
        Friend ReadOnly Property InsertDataScriptInfo() As String
            Get
                Return ResourceManager.GetString("InsertDataScriptInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE dbo.DataScriptInfo
        '''SET ExecutedDate = &apos;{1}&apos;, [Hash] = &apos;{2}&apos;
        '''WHERE Id = &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property UpdateDataScriptInfo() As String
            Get
                Return ResourceManager.GetString("UpdateDataScriptInfo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
